// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRIM51AFVODD4cx2zFmF4H-9fKjnr6y5Y',
    appId: '1:446730975235:web:d9a75bfbd25947f543b636',
    messagingSenderId: '446730975235',
    projectId: 'staff-data-labtest',
    authDomain: 'staff-data-labtest.firebaseapp.com',
    storageBucket: 'staff-data-labtest.firebasestorage.app',
    measurementId: 'G-NHH0002Q0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd7Sos6xZCiCfxasFtiDBpMGOm6QTKo-c',
    appId: '1:446730975235:android:730d4900f944524b43b636',
    messagingSenderId: '446730975235',
    projectId: 'staff-data-labtest',
    storageBucket: 'staff-data-labtest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn5Ag_LN4AI0VDS3Llty3WZc3t5UYfBIM',
    appId: '1:446730975235:ios:c71b7492ded44ef643b636',
    messagingSenderId: '446730975235',
    projectId: 'staff-data-labtest',
    storageBucket: 'staff-data-labtest.firebasestorage.app',
    iosBundleId: 'com.example.staffDataLabtest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn5Ag_LN4AI0VDS3Llty3WZc3t5UYfBIM',
    appId: '1:446730975235:ios:c71b7492ded44ef643b636',
    messagingSenderId: '446730975235',
    projectId: 'staff-data-labtest',
    storageBucket: 'staff-data-labtest.firebasestorage.app',
    iosBundleId: 'com.example.staffDataLabtest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRIM51AFVODD4cx2zFmF4H-9fKjnr6y5Y',
    appId: '1:446730975235:web:bd222b695265a99143b636',
    messagingSenderId: '446730975235',
    projectId: 'staff-data-labtest',
    authDomain: 'staff-data-labtest.firebaseapp.com',
    storageBucket: 'staff-data-labtest.firebasestorage.app',
    measurementId: 'G-YPCXH32X0K',
  );
}
